### ISSUE TITLE
SIARD 2.1 --> Microsoft SQL --> SIARD 2.1: metadata elements <description>, <archiver>, <archiverContact> not existent after export

### ISSUE THREAD

**Issue by ibbenz** [sfa-siard/SiardGui#56] opened 2023-04-03 11:35 UTC
**Issue:**

A SIARD 2.1-file is imported in Microsoft SQL and afterwards exported to SIARD 2.1.
The dbptk-Validator error message for the exported file is:
 A_M_5.1-1-3: [ERROR] : The description is mandatory inside metadata.xml dbname:(...)
 A_M_5.1-1-4: [ERROR] : The archiver is mandatory inside metadata.xml dbname:(...)
 A_M_5.1-1-5: [ERROR] : The archiverContact is mandatory inside metadata.xml dbname:(...)

**Process:**
Upload data from 0_1-3_Northwind_simple_220913_B5_2d1.siard into a Microsoft SQL database.
Download the data from the database with Siard Suite 2.1 into a SIARD 2.1 file.

**SIARD file which was uploaded:**
[0_1-3_Northwind_simple_220913_B5_2d1.zip](https://github.com/sfa-siard/SiardGui/files/11137753/0_1-3_Northwind_simple_220913_B5_2d1.zip)

**SIARD file which was downloaded:**
[1_4b_Northwind_simple_220913_B_2d1.zip](https://github.com/sfa-siard/SiardGui/files/11137751/1_4b_Northwind_simple_220913_B_2d1.zip)

**Comment by mburri** [comment] 2023-04-03 14:48
duplicate of #54 , but for mssql

**Comment by mburri** [comment] 2023-08-16 13:32
Will be resolved with the new SIARD Suite 2.2.134 (https://github.com/sfa-siard/siard-suite)

**Closed by mburri** 2023-08-16 13:32 UTC
Labels: wontfix
