### ISSUE TITLE
SIARD 2.1 --> PostgreSQL --> SIARD 2.1: loss of foreign keys 

### ISSUE THREAD

**Issue by ibbenz** [sfa-siard/SiardGui#53] opened 2023-04-03 11:12 UTC
**Issue**:
A SIARD 2.1 file is uploaded to a PostgreSQL-Database.
The foreign keys are lost during this process.

**Process**:
Upload data from 0_1-3_Northwind_simple_220913_B5_2d1.siard into a PostgreSQL database
Notice that the keys present in the SIARD-file were not created in the PostgreSQL database.
See for example: table5 ("products") in the attached file.

**SIARD file which was uploaded:**
[0_1-3_Northwind_simple_220913_B5_2d1.zip](https://github.com/sfa-siard/SiardGui/files/11137642/0_1-3_Northwind_simple_220913_B5_2d1.zip)

**Comment by sdbuehlmann** [comment] 2023-09-07 12:11
Hi @ibbenz, thanks for your report.

I got a bit confused while trying to reproduce the reported issue. When I try to upload the provided file, the Siard-Suite reports the error "No primary key found." This seems to be the intended behavior because there is no primary key defined for the table "order details." As mentioned [here](https://github.com/sfa-siard/SiardGui/issues/46#issuecomment-1261989560), this is a known restriction of the Siard-Suite (a primary key is mandatory).

Did I miss something?

**Comment by sdbuehlmann** [comment] 2023-09-07 12:54
If I remove the table with the missing primary key, then I am able to upload the data into a PostgreSQL database. As you mentioned, the foreign keys are missing in the database.

Let me analyze this for a moment, and I will get back to you.

**Comment by sdbuehlmann** [comment] 2023-09-25 13:11
Hi @ibbenz, if I just remove this illegal table, other issues are appearing (missing columns in foreign keys). I have no clue if that is a problem with the software or if your SIARD archive has multiple issues. Could you please ensure that your SIARD archive is valid and upload it here again? Thank you.

**Comment by sdbuehlmann** [comment] 2024-01-11 16:03
Hi @ibbenz,

I've temporarily fixed your project (there were two problems: The missing primary key of the table "order details" and also the whitespace in that table name. Both problems were caused by the used Postgres JDBC driver. Please try to follow common SQL best practices when setting up archives).

Nevertheless, I can confirm that there is a bug, and all foreign keys are lost during uploading an archive. It seems to be a problem with the case-sensitivity of Postgres. This will be addressed with issue [SiardCmd#31](https://github.com/sfa-siard/SiardCmd/issues/31). Because of that, I close this issue as a duplicate.

**Closed** 2024-01-11 16:03 UTC
Labels: bug, duplicate
