### ISSUE TITLE
SIARD 1.2 ---> POSTGRESQL or Microsoft SQL --> SIARD 2.2: Archive is invalid

### ISSUE THREAD

**Issue by ibbenz** [sfa-siard/SiardGui#59] opened 2023-04-03 12:18 UTC
**Issue:**
Downloading data from a POSTGRESQL or Microsoft SQL Database results in
error message: _error: Archive is invalid_

**Process:**
Upload data from 0_1-3_Northwind_simple_220913_B5_2d1.siard (original) into a Microsoft SQL database with Siard Suite 2.1. 
Try to download it in a SIARD 2.2 file with Siard Suite 2.2.11.

**SIARD file which was uploaded:**
[0_1-3_Northwind_simple_220913_B5_2d1.zip](https://github.com/sfa-siard/SiardGui/files/11137860/0_1-3_Northwind_simple_220913_B5_2d1.zip)

**Comment by mburri** [comment] 2023-04-03 14:52
Thank you for the error report.

we will check try to reproduce the issue and look into it.

**Comment by sdbuehlmann** [comment] 2024-01-08 12:29
Hi @ibbenz,

Here is some new information about your bug report:

- In the provided SIARD file "0_1-3_Northwind_simple_220913_B5_2d1.zip" (please note, a SIARD file should have the file ending ".siard") there is no primary key defined for the table "order details." Even though, it is a valid SIARD archive (in the spec, the primary key for a table is explicitly marked as "optional"). But it is a well-known "best practice" to use primary keys when working with relational databases. SIARD-Suite is currently designed and built according to this best-practice. You can get unexpected errors and misbehavings if you work without primary keys.
- Even when POSTGRESQL enables it to work without a primary key, the corresponding JDBC driver does not. A ResultSet of a table without a primary key is always "read-only," so with the current implementation of SIARD-Suite, you cannot upload the provided file to a PostgreSQL database.
- As you've described, it works with a Microsoft SQL Database. I've tested it [here](https://github.com/sfa-siard/SiardCmd/compare/main...issue/siardgui%2359_invalid_archive) with the newest version of SiardCmd. The upload and download worked without any exceptions, and the downloaded archive is valid.

So unfortunately, we cannot reproduce the issue as it is described in your report. Because of that, we will close this report without any further actions (Well, there are some actions: We need to describe the limitation of the required primary key better in the corresponding readme's). Your patience and cooperation are highly appreciated.

**Closed by sdbuehlmann** 2024-01-08 12:29 UTC
Labels: bug
