### ISSUE TITLE
How SIARD handle datetime in specific format

### ISSUE THREAD

**Issue by PeterChan1** [sfa-siard/SiardGui#45] opened 2022-09-26 01:53 UTC
Hello, May I know if it is feasible to instruct how SIARD handle datetime in specific format?

For example, it has a Microsoft Access database storing the date and time in form of DD/MM/YYYY HH:MM:SS

![image](https://user-images.githubusercontent.com/114372030/192178554-cc4f0857-c189-4a5e-a357-ca0119b24816.png)

The date and time format become MM/DD/YY HH:MM AM/PM under SIARD:
![image](https://user-images.githubusercontent.com/114372030/192178570-cedfa3d1-f79b-471d-be0f-9a4ecd60f0fe.png)

Please share if SIARD would handle datetime in specific format.  If so, is the format configurable? 
I checked, but it seems not following the date time settings configured on the computer where SIARD run.  Thank You.

**Comment by walkerjan** [comment] 2022-09-27 09:15
Hello @PeterChan1

You have to distinguish: (1) the format in which the data of a SIARD archive is presented to the user in the GUI from (2) the format in which the data is stored in the XML files of a SIARD archive.

(1) The format in which datetimes are presented to the users in the table preview of the GUI is MM/DD/YY HH:MM (as you mentioned) and cannot be configured in the options menu of the GUI.

(2) The format (regex pattern \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z?) in which datetimes are stored inside a SIARD archive is specified in the respective table.xsd file, as you can investigate by browsing through an example archive.

I hope this answers your question.

**Comment by PeterChan1** [comment] 2022-10-14 03:07
Hello @walkerjan 

Thanks for the information.
I located the table.xsd file after unzipping the .siard file.
And then I customized the date time format in table.xsd, modified the raw data to in line with date time format specified.
I zipped and packed it as .siard file in an attempt to upload the content into target database. However, it returned with error that the .siard file is invalid.

![image](https://user-images.githubusercontent.com/114372030/195753228-6b74ce31-6f4b-4f45-8334-442b5af75994.png)

Would you mind sharing how to edit the table.xsd file that lead to successful import?

Thank You.

**Comment by walkerjan** [comment] 2022-10-17 15:08
Hello @PeterChan1

Can you please share your example SIARD archive so that we can try to spot the error in your specification. Thanks.

**Comment by PeterChan1** [comment] 2022-10-25 08:21
Hello @walkerjan 

Enclosed please find the original and modified siard files.

[siard files.zip](https://github.com/sfa-siard/SiardGui/files/9858421/siard.files.zip)

As a trial, I tried to change the date time format from original YYYY-MM-DD HH:DD:SS format to DD-MM-YYYY one.

Enclosed please find the changes made to the new SIARD file for reference. Thank You.

content\schema0\table0\table0.xml: 
<c3>15-07-2019Z</c3>
<c3>18-06-2022Z</c3>
<c3>27-12-2021Z</c3>

content\schema0\table0\table0.xsd:
  <xs:simpleType name="dateTimeType">
    <xs:restriction base="xs:dateTime">
      <xs:minInclusive value="01-01-0001"/>
      <xs:maxExclusive value="01-01-10000"/>
      <xs:pattern value="\d{2}-\d{2}-\d{4}Z?"/>
    </xs:restriction>
  </xs:simpleType>

header\table.xsd:
  <xs:simpleType name="dateTimeType">
    <xs:restriction base="xs:dateTime">
      <xs:minInclusive value="01-01-0001"/>
      <xs:maxExclusive value="01-01-10000"/>
      <xs:pattern value="\d{2}-\d{2}-\d{4}Z?"/>
    </xs:restriction>
  </xs:simpleType>

**Comment by StephGit** [comment] 2022-11-29 10:16
Hello @PeterChan1 

**(1)** As @walkerjan  mentioned the format in the table preview of the GUI  cannot be configured - but should represent the settings of your system. To customize this setting via the options would be an enhancement. 

For example a screenshot of your original file on my system:
![2022-11-29_11-07](https://user-images.githubusercontent.com/24672636/204500368-bd83bffe-4add-41fa-8a2a-fa7fa9a9d0b6.png)


**(2)** The format in which datetimes ect.  are stored inside a SIARD archive is specified through the [Schema](https://www.w3.org/TR/NOTE-datetime). Your schema definition is not valid.

**Comment by mburri** [comment] 2023-08-17 10:06
System settings determine the format in which data is displayed. This 
cannot be configured in the application.

It is not recommended to make manual adjustments within the SIARD 
archive to change the date format, as this may result in invalid archive 
files.

As this is not a bug in the application, we close this issue.

**Closed** 2023-08-17 10:07 UTC
Labels: enhancement
