### ISSUE TITLE
Siard Suite download all DB instead of selected MySQL-DB into .siard

### ISSUE THREAD

**Issue by ibbenz** [sfa-siard/SiardGui#33] opened 2022-08-08 07:58 UTC
Siard Suite downloads all databases from a server instead of the selected one (database connection in Siard Suite). I used the MySQL-Server of MySQL-Workbench 8.0 and the MySQL-Server of XAMPP.
In each case all DB instead of the selected one were downloaded into .siard.

The following images illustrate the issue:
![ChosenDatabase](https://user-images.githubusercontent.com/58251561/183368471-afbf97a2-ed4d-4cdf-89ed-d7acaf815dc4.png)

The selected DB is siardsimple (database connection in Siard Suite).
![Downloaded_Databases_MySQL_Workbench](https://user-images.githubusercontent.com/58251561/183368503-7ec17616-ef26-411a-a7a5-65aa8ab768fa.png)

![Downloaded_Databases_MySQL_Workbench](https://user-images.githubusercontent.com/58251561/183368542-72ab29c2-a445-44da-985e-4bc6c9592fb9.png)

**Comment by walkerjan** [comment] 2022-08-11 08:39
Thanks a lot for reporting this issue.

We shall investigate it and consider respective measures to be taken.

**Comment by sdbuehlmann** [comment] 2023-11-13 14:53
Duplicate of https://github.com/sfa-siard/SiardCmd/issues/14

**Closed by sdbuehlmann** 2023-11-13 14:53 UTC
Labels: bug
