### ISSUE TITLE
Performance issue with gui 2.1.127

### ISSUE THREAD

**Issue by mezeijozsef** [sfa-siard/SiardGui#17] opened 2020-03-11 19:57 UTC
Let me share my recent experience. 
We have two databases around 341MB. I used MS Access to "convert" mdb to accdb because this is the format SiardGui 2.1.127 can use. 
I started creating a siard package from one of the database file. After 36 hours it became very slow for no reason.

This is the fourth time I started this process, but somehow it always just stops before the end (maybe some windows service closes it?).

I was asked to post this issue here. 
My PC isn't the fastest, but it would do the job. Intel i5 3470, hyperx sata 3 ssd 500GB, 8gb of hyperx ddr3 memory. Windows 10.

![tasklist](https://user-images.githubusercontent.com/19432723/76458059-34ea1d80-63da-11ea-8413-cfdb4c290096.JPG)
![beginning](https://user-images.githubusercontent.com/19432723/76458061-3582b400-63da-11ea-82dd-47dd0ac8d737.JPG)
![after 36 hour of running](https://user-images.githubusercontent.com/19432723/76458062-361b4a80-63da-11ea-89d6-0f0750686f29.JPG)

**Comment by HartwigThomas** [comment] 2020-03-17 08:03
This appears to be a very strange effect.
Maybe the problem is in the data and it is not a performance problem but a failure?
Otherwise one might try with more heap space (see manual).
If you can make the DB available to me, I could try it myself. (ZIP with encryption preserves condidentiality. I shall only use it for debugging and delete it afterwards.)

**Comment by HartwigThomas** [comment] 2020-09-23 14:57
Closing this issue for lack of information.

**Closed by HartwigThomas** 2020-09-23 14:57 UTC
